name: pdfxblock

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.5]
        tox-env:
          - quality
          - py35-django22
    steps:
     - uses: actions/checkout@v2
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v2
       with:
         python-version: ${{ matrix.python-version }}
     - name: Install dependencies
       run: |
         pip install tox
     - name: Test with tox
       run: tox -e ${{ matrix.tox-env }}
